app = "asn-technologies-hrms"
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

    [[services.ports]]
      handlers = ["tls"]
      port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[processes]]
    script = "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment = {
      PORT = "8000"
    }

